---
title: "Elyse EDA Updated"
author: "Elyse McFalls"
date: "2023-11-09"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

```{r}
library(tidyverse)
library(ggpubr)
```

## Loading Data

```{r}
women <- read.csv('cleaned data/restricted_women_2023.csv')
men <- read.csv('cleaned data/restricted_men_2023.csv')
all <- read.csv('cleaned data/full_data_2023.csv')
```


## Women's Data
### Vault

```{r}
women_vt <- women%>%
  filter(stringr::str_like(Apparatus,'VT%') & Rank <= 5)
```


```{r}
# best average scores
women_vt_summary <- women_vt %>%
  group_by(FullName, Country) %>%
  summarise(avg_score = mean(Score), min_score = min(Score), max_score = max(Score)) 

head(women_vt_summary)
```

```{r fig.width=7}
vt_avg <- women_vt_summary %>%
  ungroup() %>%
  arrange(desc(avg_score)) %>%
  slice(1:5) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, avg_score), x = avg_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Average Score",
       y = "Athlete", x = "Average Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y") 

vt_best <- women_vt_summary %>%
  ungroup() %>%
  #group_by(Country) %>%
  arrange(desc(max_score)) %>%
  slice(1:5) %>%
  #ungroup() %>%
  #arrange(desc(min_score)) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, max_score), x = max_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Best Score",
       y = "Athlete", x = "Best Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y")

vt_worst <- women_vt_summary %>%
  ungroup() %>%
  #group_by(Country) %>%
  arrange(desc(min_score)) %>%
  slice(1:5) %>%
  #ungroup() %>%
  #arrange(desc(min_score)) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, min_score), x = min_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Worst Score",
       y = "Athlete", x = "Worst Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y") 
```

```{r fig.height=8, fig.width=16}
vt_eda <- ggpubr::ggarrange(vt_worst, vt_avg, vt_best, ncol = 3, common.legend = T)
vt_eda <- ggpubr::annotate_figure(vt_eda, top = text_grob("Top 5 Female Athletes by Vault Scores in 2022-2023", size = 18))
vt_eda
```


### Balance Beam

```{r}
women_bb <- women%>%
  filter(stringr::str_like(Apparatus,'BB%'))
```


```{r}
# best average scores
women_bb_summary <- women_bb %>%
  group_by(FullName, Country) %>%
  summarise(avg_score = mean(Score), min_score = min(Score), max_score = max(Score)) 

head(women_bb_summary)
```

```{r fig.width=7}
bb_avg <- women_bb_summary %>%
  ungroup() %>%
  arrange(desc(avg_score)) %>%
  slice(1:5) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, avg_score), x = avg_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Average Score",
       y = "Athlete", x = "Average Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y") 

bb_best <- women_bb_summary %>%
  ungroup() %>%
  #group_by(Country) %>%
  arrange(desc(max_score)) %>%
  slice(1:5) %>%
  #ungroup() %>%
  #arrange(desc(min_score)) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, max_score), x = max_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Best Score",
       y = "Athlete", x = "Best Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y")

bb_worst <- women_bb_summary %>%
  ungroup() %>%
  #group_by(Country) %>%
  arrange(desc(min_score)) %>%
  slice(1:5) %>%
  #ungroup() %>%
  #arrange(desc(min_score)) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, min_score), x = min_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Worst Score",
       y = "Athlete", x = "Worst Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y") 
```

```{r fig.height=8, fig.width=16}
bb_eda <- ggpubr::ggarrange(bb_worst, bb_avg, bb_best, ncol = 3, common.legend = T)
bb_eda <- ggpubr::annotate_figure(bb_eda, top = text_grob("Top 5 Female Athletes by Balance Beam Scores in 2022-2023", size = 18))
bb_eda
```


### Floor Exercises 

```{r}
women_fx <- women%>%
  filter(stringr::str_like(Apparatus,'FX%'))
```

```{r}
# best average scores
women_fx_summary <- women_fx %>%
  group_by(FullName, Country) %>%
  summarise(avg_score = mean(Score), min_score = min(Score), max_score = max(Score)) 

head(women_fx_summary)
```

```{r fig.width=7}
fx_avg <- women_fx_summary %>%
  ungroup() %>%
  arrange(desc(avg_score)) %>%
  slice(1:5) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, avg_score), x = avg_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Average Score",
       y = "Athlete", x = "Average Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y") 

fx_best <- women_fx_summary %>%
  ungroup() %>%
  #group_by(Country) %>%
  arrange(desc(max_score)) %>%
  slice(1:5) %>%
  #ungroup() %>%
  #arrange(desc(min_score)) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, max_score), x = max_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Best Score",
       y = "Athlete", x = "Best Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y")

fx_worst <- women_fx_summary %>%
  ungroup() %>%
  #group_by(Country) %>%
  arrange(desc(min_score)) %>%
  slice(1:5) %>%
  #ungroup() %>%
  #arrange(desc(min_score)) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, min_score), x = min_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Worst Score",
       y = "Athlete", x = "Worst Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y") 
```

```{r fig.height=8, fig.width=16}
fx_eda <- ggpubr::ggarrange(fx_worst, fx_avg, fx_best, ncol = 3, common.legend = T)
fx_eda <- ggpubr::annotate_figure(fx_eda, top = text_grob("Top 5 Female Athletes by Floor Scores in 2022-2023", size = 18))
fx_eda
```

### Uneven Bars

```{r}
women_ub <- women%>%
  filter(stringr::str_like(Apparatus,'UB%'))
```

```{r}
# best average scores
women_ub_summary <- women_ub %>%
  group_by(FullName, Country) %>%
  summarise(avg_score = mean(Score), min_score = min(Score), max_score = max(Score)) 

head(women_ub_summary)
```


```{r fig.width=7}
ub_avg <- women_ub_summary %>%
  ungroup() %>%
  arrange(desc(avg_score)) %>%
  slice(1:5) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, avg_score), x = avg_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Average Score",
       y = "Athlete", x = "Average Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y") 

ub_best <- women_ub_summary %>%
  ungroup() %>%
  #group_by(Country) %>%
  arrange(desc(max_score)) %>%
  slice(1:5) %>%
  #ungroup() %>%
  #arrange(desc(min_score)) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, max_score), x = max_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Best Score",
       y = "Athlete", x = "Best Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y")

ub_worst <- women_ub_summary %>%
  ungroup() %>%
  #group_by(Country) %>%
  arrange(desc(min_score)) %>%
  slice(1:5) %>%
  #ungroup() %>%
  #arrange(desc(min_score)) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, min_score), x = min_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Worst Score",
       y = "Athlete", x = "Worst Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y") 
```

```{r fig.height=8, fig.width=16}
ub_eda <- ggpubr::ggarrange(ub_worst, ub_avg, ub_best, ncol = 3, common.legend = T)
ub_eda <- ggpubr::annotate_figure(ub_eda, top = text_grob("Top 5 Female Athletes by Uneven Bar Scores in 2022-2023", size = 18))
ub_eda
```











## Men's Data

### Vault


```{r}
men_vt <- men%>%
  filter(stringr::str_like(Apparatus,'VT%') & Rank <= 5)

men_vt_summary <- men_vt %>%
  group_by(FullName, Country) %>%
  summarise(avg_score = mean(Score), min_score = min(Score), max_score = max(Score)) 

head(men_vt_summary)
```

```{r fig.width=7}
vt_avg <- men_vt_summary %>%
  ungroup() %>%
  arrange(desc(avg_score)) %>%
  slice(1:5) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, avg_score), x = avg_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Average Score",
       y = "Athlete", x = "Average Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y") 

vt_best <- men_vt_summary %>%
  ungroup() %>%
  #group_by(Country) %>%
  arrange(desc(max_score)) %>%
  slice(1:5) %>%
  #ungroup() %>%
  #arrange(desc(min_score)) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, max_score), x = max_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Best Score",
       y = "Athlete", x = "Best Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y")

vt_worst <- men_vt_summary %>%
  ungroup() %>%
  #group_by(Country) %>%
  arrange(desc(min_score)) %>%
  slice(1:5) %>%
  #ungroup() %>%
  #arrange(desc(min_score)) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, min_score), x = min_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Worst Score",
       y = "Athlete", x = "Worst Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y") 
```

```{r fig.height=8, fig.width=16}
vt_eda <- ggpubr::ggarrange(vt_worst, vt_avg, vt_best, ncol = 3, common.legend = T)
vt_eda <- ggpubr::annotate_figure(vt_eda, top = text_grob("Top 5 Male Athletes by Vault Scores in 2022-2023", size = 18))
vt_eda
```


### Pommel Horse


```{r}
men_ph <- men%>%
  filter(stringr::str_like(Apparatus,'PH%') & Rank <= 5)

men_ph_summary <- men_ph %>%
  group_by(FullName, Country) %>%
  summarise(avg_score = mean(Score), min_score = min(Score), max_score = max(Score)) 

head(men_ph_summary)
```

```{r fig.width=7}
ph_avg <- men_ph_summary %>%
  ungroup() %>%
  arrange(desc(avg_score)) %>%
  slice(1:5) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, avg_score), x = avg_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Average Score",
       y = "Athlete", x = "Average Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y") 

ph_best <- men_ph_summary %>%
  ungroup() %>%
  #group_by(Country) %>%
  arrange(desc(max_score)) %>%
  slice(1:5) %>%
  #ungroup() %>%
  #arrange(desc(min_score)) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, max_score), x = max_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Best Score",
       y = "Athlete", x = "Best Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y")

ph_worst <- men_ph_summary %>%
  ungroup() %>%
  #group_by(Country) %>%
  arrange(desc(min_score)) %>%
  slice(1:5) %>%
  #ungroup() %>%
  #arrange(desc(min_score)) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, min_score), x = min_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Worst Score",
       y = "Athlete", x = "Worst Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y") 
```

```{r fig.height=8, fig.width=16}
ph_eda <- ggpubr::ggarrange(ph_worst, ph_avg, ph_best, ncol = 3, common.legend = T)
ph_eda <- ggpubr::annotate_figure(ph_eda, top = text_grob("Top 5 Male Athletes by Pommel Horse Scores in 2022-2023", size = 18))
ph_eda
```


### Horizontal Bar


```{r}
men_hb <- men%>%
  filter(stringr::str_like(Apparatus,'HB%') & Rank <= 5)

men_hb_summary <- men_hb %>%
  group_by(FullName, Country) %>%
  summarise(avg_score = mean(Score), min_score = min(Score), max_score = max(Score)) 

head(men_hb_summary)
```

```{r fig.width=7}
hb_avg <- men_hb_summary %>%
  ungroup() %>%
  arrange(desc(avg_score)) %>%
  slice(1:5) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, avg_score), x = avg_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Average Score",
       y = "Athlete", x = "Average Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y") 

hb_best <- men_hb_summary %>%
  ungroup() %>%
  #group_by(Country) %>%
  arrange(desc(max_score)) %>%
  slice(1:5) %>%
  #ungroup() %>%
  #arrange(desc(min_score)) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, max_score), x = max_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Best Score",
       y = "Athlete", x = "Best Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y")

hb_worst <- men_hb_summary %>%
  ungroup() %>%
  #group_by(Country) %>%
  arrange(desc(min_score)) %>%
  slice(1:5) %>%
  #ungroup() %>%
  #arrange(desc(min_score)) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, min_score), x = min_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Worst Score",
       y = "Athlete", x = "Worst Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y") 
```

```{r fig.height=8, fig.width=16}
hb_eda <- ggpubr::ggarrange(hb_worst, ph_avg, ph_best, ncol = 3, common.legend = T)
hb_eda <- ggpubr::annotate_figure(hb_eda, top = text_grob("Top 5 Male Athletes by Horizontal Bar Scores in 2022-2023", size = 18))
hb_eda
```

### Floor


```{r}
men_fx <- men%>%
  filter(stringr::str_like(Apparatus,'FX%') & Rank <= 5)

men_fx_summary <- men_fx %>%
  group_by(FullName, Country) %>%
  summarise(avg_score = mean(Score), min_score = min(Score), max_score = max(Score)) 

head(men_fx_summary)
```

```{r fig.width=7}
fx_avg <- men_fx_summary %>%
  ungroup() %>%
  arrange(desc(avg_score)) %>%
  slice(1:5) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, avg_score), x = avg_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Average Score",
       y = "Athlete", x = "Average Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y") 

fx_best <- men_fx_summary %>%
  ungroup() %>%
  #group_by(Country) %>%
  arrange(desc(max_score)) %>%
  slice(1:5) %>%
  #ungroup() %>%
  #arrange(desc(min_score)) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, max_score), x = max_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Best Score",
       y = "Athlete", x = "Best Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y")

fx_worst <- men_fx_summary %>%
  ungroup() %>%
  #group_by(Country) %>%
  arrange(desc(min_score)) %>%
  slice(1:5) %>%
  #ungroup() %>%
  #arrange(desc(min_score)) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, min_score), x = min_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Worst Score",
       y = "Athlete", x = "Worst Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y") 
```

```{r fig.height=8, fig.width=16}
fx_eda <- ggpubr::ggarrange(fx_worst, fx_avg, fx_best, ncol = 3, common.legend = T)
fx_eda <- ggpubr::annotate_figure(fx_eda, top = text_grob("Top 5 Male Athletes by Floor Scores in 2022-2023", size = 18))
fx_eda
```


### Parallel Bars


```{r}
men_pb <- men%>%
  filter(stringr::str_like(Apparatus,'PB%') & Rank <= 5)

men_pb_summary <- men_pb %>%
  group_by(FullName, Country) %>%
  summarise(avg_score = mean(Score), min_score = min(Score), max_score = max(Score)) 

head(men_pb_summary)
```

```{r fig.width=7}
pb_avg <- men_pb_summary %>%
  ungroup() %>%
  arrange(desc(avg_score)) %>%
  slice(1:5) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, avg_score), x = avg_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Average Score",
       y = "Athlete", x = "Average Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y") 

pb_best <- men_pb_summary %>%
  ungroup() %>%
  #group_by(Country) %>%
  arrange(desc(max_score)) %>%
  slice(1:5) %>%
  #ungroup() %>%
  #arrange(desc(min_score)) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, max_score), x = max_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Best Score",
       y = "Athlete", x = "Best Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y")

pb_worst <- men_pb_summary %>%
  ungroup() %>%
  #group_by(Country) %>%
  arrange(desc(min_score)) %>%
  slice(1:5) %>%
  #ungroup() %>%
  #arrange(desc(min_score)) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, min_score), x = min_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Worst Score",
       y = "Athlete", x = "Worst Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y") 
```

```{r fig.height=8, fig.width=16}
pb_eda <- ggpubr::ggarrange(pb_worst, pb_avg, pb_best, ncol = 3, common.legend = T)
pb_eda <- ggpubr::annotate_figure(pb_eda, top = text_grob("Top 5 Male Athletes by Parallel Bar Scores in 2022-2023", size = 18))
pb_eda
```


### Still Rings


```{r}
men_sr <- men%>%
  filter(stringr::str_like(Apparatus,'PB%') & Rank <= 5)

men_sr_summary <- men_sr %>%
  group_by(FullName, Country) %>%
  summarise(avg_score = mean(Score), min_score = min(Score), max_score = max(Score)) 

head(men_sr_summary)
```

```{r fig.width=7}
sr_avg <- men_sr_summary %>%
  ungroup() %>%
  arrange(desc(avg_score)) %>%
  slice(1:5) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, avg_score), x = avg_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Average Score",
       y = "Athlete", x = "Average Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y") 

sr_best <- men_sr_summary %>%
  ungroup() %>%
  #group_by(Country) %>%
  arrange(desc(max_score)) %>%
  slice(1:5) %>%
  #ungroup() %>%
  #arrange(desc(min_score)) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, max_score), x = max_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Best Score",
       y = "Athlete", x = "Best Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y")

sr_worst <- men_sr_summary %>%
  ungroup() %>%
  #group_by(Country) %>%
  arrange(desc(min_score)) %>%
  slice(1:5) %>%
  #ungroup() %>%
  #arrange(desc(min_score)) %>%
  mutate(rank = ifelse(row_number() <= 5, row_number(), NA), rank = as.factor(rank)) %>%
  ggplot(aes(y= reorder(FullName, min_score), x = min_score, fill = rank)) +
  geom_col(stat = "identity") +
  labs(title = "Top Athletes by Worst Score",
       y = "Athlete", x = "Worst Score") +
  facet_wrap(~factor(Country, unique(Country)), ncol = 1, scales = "free_y") 
```

```{r fig.height=8, fig.width=16}
sr_eda <- ggpubr::ggarrange(sr_worst, sr_avg, sr_best, ncol = 3, common.legend = T)
  sr_eda <- ggpubr::annotate_figure(sr_eda, top = text_grob("Top 5 Male Athletes by Still Ring Scores in 2022-2023", size = 18))
sr_eda
```










