---
title: "evan"
subtitle: "no subtitle"
author: "evan"
format: 
  html:
    self-contained: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Setup
```{r setup, include=FALSE}
library(tidyverse)
library(data.table)
library(ggplot2)
library(purrr)
library(dplyr)
```


## 11.13.2023 (MON) - 7PM - THE SIMULATION ALGO - WOMEN



## THE SET-UP BEFORE THE ALGO
```{r}
## Re-arranged data
data_women_scores_2022_to_2023 <- read.csv("cleaned data/restricted_women_2023.csv") %>% 
  select(Country, FullName, Apparatus, Score) %>% 
  # first, making c(VT, VT1, VT2) all just VT, since they're all the same apparatus, just named different at different competitions
  mutate(Apparatus = ifelse(Apparatus %in% c("VT1", "VT2"), "VT", Apparatus))  %>%
  filter(!is.na(Score) & Score != 0) #dropping all NAs -- ask the team: should we also drop zeros? -> emily said yeah 11.13.2023 7 21pm


# this is the data that will feed into the algo
data_ready_for_algo <- data_women_scores_2022_to_2023 %>%
  group_by(Country, FullName, Apparatus) %>%
  summarise(Scores = list(Score), .groups = 'drop')




## Global Fixed Integers
minBBScoreIn_data_women_scores_2022_to_2023 <- min(data_women_scores_2022_to_2023$Score[data_women_scores_2022_to_2023$Apparatus == "BB"], na.rm = TRUE)
maxBBScoreIn_data_women_scores_2022_to_2023 <- max(data_women_scores_2022_to_2023$Score[data_women_scores_2022_to_2023$Apparatus == "BB"], na.rm = TRUE)

minFXScoreIn_data_women_scores_2022_to_2023 <- min(data_women_scores_2022_to_2023$Score[data_women_scores_2022_to_2023$Apparatus == "FX"], na.rm = TRUE)
maxFXScoreIn_data_women_scores_2022_to_2023 <- max(data_women_scores_2022_to_2023$Score[data_women_scores_2022_to_2023$Apparatus == "FX"], na.rm = TRUE)

minUBScoreIn_data_women_scores_2022_to_2023 <- min(data_women_scores_2022_to_2023$Score[data_women_scores_2022_to_2023$Apparatus == "UB"], na.rm = TRUE)
maxUBScoreIn_data_women_scores_2022_to_2023 <- max(data_women_scores_2022_to_2023$Score[data_women_scores_2022_to_2023$Apparatus == "UB"], na.rm = TRUE)

minVTScoreIn_data_women_scores_2022_to_2023 <- min(data_women_scores_2022_to_2023$Score[data_women_scores_2022_to_2023$Apparatus == "VT"], na.rm = TRUE)
maxVTScoreIn_data_women_scores_2022_to_2023 <- max(data_women_scores_2022_to_2023$Score[data_women_scores_2022_to_2023$Apparatus == "VT"], na.rm = TRUE)


## 2D Table of Global Fixed Integers
minAndMaxScores2DTable <- list(
    BB = list(
        min = minBBScoreIn_data_women_scores_2022_to_2023,
        max = maxBBScoreIn_data_women_scores_2022_to_2023
    ),
    FX = list(
        min = minFXScoreIn_data_women_scores_2022_to_2023,
        max = maxFXScoreIn_data_women_scores_2022_to_2023
    ),
    UB = list(
        min = minUBScoreIn_data_women_scores_2022_to_2023,
        max = maxUBScoreIn_data_women_scores_2022_to_2023
    ),
    VT = list(
        min = minVTScoreIn_data_women_scores_2022_to_2023,
        max = maxVTScoreIn_data_women_scores_2022_to_2023
    )
)


## TO BE FED INTO runOlympicsNTimes
allWomenBBParticipants <- data_ready_for_algo %>%
  select(Country, FullName, Apparatus) %>%
  unique() %>% 
  filter(Apparatus == "BB")

allWomenUBParticipants <- data_ready_for_algo %>%
  select(Country, FullName, Apparatus) %>%
  unique() %>% 
  filter(Apparatus == "UB")

allWomenFXParticipants <- data_ready_for_algo %>%
  select(Country, FullName, Apparatus) %>%
  unique() %>% 
  filter(Apparatus == "FX")

allWomenVTParticipants <- data_ready_for_algo %>%
  select(Country, FullName, Apparatus) %>%
  unique() %>% 
  filter(Apparatus == "VT")

allWomenBBParticipants <- allWomenBBParticipants %>%
  mutate(SimulationResults = lapply(seq_along(FullName), function(x) list()))

allWomenUBParticipants <- allWomenUBParticipants %>%
  mutate(SimulationResults = lapply(seq_along(FullName), function(x) list()))

allWomenFXParticipants <- allWomenFXParticipants %>%
  mutate(SimulationResults = lapply(seq_along(FullName), function(x) list()))

allWomenVTParticipants <- allWomenVTParticipants %>%
  mutate(SimulationResults = lapply(seq_along(FullName), function(x) list()))
```

```{r}
# sanity checking the 2D Table
# minAndMaxScores2DTable$BB$min
```



## HELPER FUNCTION: createProperDataframe
```{r}
# Helper Function: createProperDataframe
# inputs are: "country code", "Athlete Name", "Apparatus (the two letters, like FX")
# output is a dataframe that is suitable for going in as input into the next step, aka creating estimated kernel densities

createProperDataframe = function(countryCode, athleteName, apparatusInitials){
  dataframeToReturn <- data_ready_for_algo %>% 
    filter(Country == countryCode, FullName == athleteName, Apparatus == apparatusInitials) %>% 
    select(Scores) %>% 
    unnest(Scores) %>% 
    unlist()
  
  apparatus <- apparatusInitials
  
  return(list(dataframeToReturn, apparatus))
}
```

```{r}
# sanity checking function: createProperDataframe
#a = createProperDataframe(countryCode = "AUS", athleteName = "BROWN GEORGIA", apparatusInitials = "FX")
#a

#print(a[[1]])

#a[[2]]

#class(a[[1]]) --> should be "numeric"
#class(a[[2]])

#a[[1]]
```


## HELPER FUNCTION: estimateKernelDensity
```{r}
# Helper Function: estimateKernelDensity

# coming up with an estimate kernel density based on the inputs that are:
# 1. output of createProperDataframe = list(properDataframeCreatedForAthleteAndApparatusCombination, apparatus)
# 2. bandwidthValue (the bigger, the "smoother")

# output:
# dataframe of x and y coordinates --> coordinates of the estimated density function

estimateKernelDensity <- function(outputOfCreateProperDataframe, bandwidthValue){
  library(KernSmooth)
  apparatusOfInterestHere = outputOfCreateProperDataframe[[2]]
  kernelLowerLimit = min(minAndMaxScores2DTable$apparatusOfInterestHere$min - 2, 0)
  kernelUpperLimit = max(minAndMaxScores2DTable$apparatusOfInterestHere$max + 2, 15.7)
  
  
  almostToReturn <- bkde(x = outputOfCreateProperDataframe[[1]], kernel = "normal", canonical = FALSE, bandwidth = bandwidthValue, gridsize = 401L, range.x = c(kernelLowerLimit, kernelUpperLimit), truncate = TRUE)
  #range.x = c(kernelLowerLimit, kernelUpperLimit)
  dataframeToReturn <- data.frame(
    x = almostToReturn$x, 
    y = almostToReturn$y
  )
  
  return(dataframeToReturn)
}

```

```{r}
# sanity checking function: estimateKernelDensity
#b = estimateKernelDensity(createProperDataframe(countryCode = "AUS", athleteName = "BROWN GEORGIA", apparatusInitials = "UB"), 0.25)
#b
#class(b)


ggplot() +
  geom_line(data = estimateKernelDensity(createProperDataframe(countryCode = "AUS", athleteName = "BROWN GEORGIA", apparatusInitials = "UB"), 0.25), aes(x, y), color = "blue")
```








## HELPER FUNCTION: createCDFfromKDEandDrawONEscore
```{r}
createCDFfromKDEandDrawONEscore <- function(dataframeReturnedByestimateKernelDensity){
  # Create a CDF from the KDE
  kde_y_cumsum <- cumsum(dataframeReturnedByestimateKernelDensity$y)
  cdf <- kde_y_cumsum / max(kde_y_cumsum)
  
  
  u <- runif(1)  # Generate uniform random number
  sampled_value <- dataframeReturnedByestimateKernelDensity$x[which.min(abs(cdf - u))]
  
  return(sampled_value)
  
  
}
```

```{r}
# sanity checking function: createCDFfromKDEandDrawONEscore
c = createCDFfromKDEandDrawONEscore(estimateKernelDensity(createProperDataframe(countryCode = "AUS", athleteName = "BROWN GEORGIA", apparatusInitials = "UB"), 0.25))
c
class(c)

emptyList <- vector("list", 3000)

for (i in 1:3000) {
  toAdd <- createCDFfromKDEandDrawONEscore(estimateKernelDensity(createProperDataframe(countryCode = "AUS", athleteName = "BROWN GEORGIA", apparatusInitials = "UB"), 0.25))
  emptyList[[i]] <- toAdd
}

emptyListDF <- data.frame(values = unlist(emptyList))

# Creating a histogram with ggplot2
ggplot(emptyListDF, aes(x = values)) +
  geom_histogram(binwidth = 0.1, fill = "blue", color = "black") +
  theme_minimal() +
  labs(title = "Histogram of Scores", x = "Score", y = "Frequency")
```

```{r}
class(allWomenBBParticipants[1, ])

allWomenBBParticipants[1, ]

allWomenBBParticipants[1, ]$Country
allWomenBBParticipants[1, ]$FullName
allWomenBBParticipants[1, ]$Apparatus

class(allWomenBBParticipants[1, ]$Country)
class(allWomenBBParticipants[1, ]$FullName)
class(allWomenBBParticipants[1, ]$Apparatus)


row1 <- allWomenBBParticipants[1, ]$SimulationResults
```


```{r}
# sanity checking inner loop in runOlympicsNTimes

#row1 <- allWomenBBParticipants[1, ]
#    emptyList1 <- vector("list", 1000)
#    for (i in 1:1000) {
#      toAdd <- createCDFfromKDEandDrawONEscore(estimateKernelDensity(createProperDataframe(countryCode = row1$Country, athleteName = row1$FullName, apparatusInitials = row1$Apparatus), 0.25))
#      emptyList1[[i]] <- toAdd
#    }
    
    
    
#emptyList1_df <- data.frame(values = unlist(emptyList1))

# Create a histogram using ggplot
#ggplot(emptyList1_df, aes(x = values)) +
#  geom_histogram(binwidth = 0.1, fill = "blue", color = "black") + # Adjust binwidth as needed
#  theme_minimal() +
#  labs(title = "Histogram of Sampled Scores", x = "Score", y = "Frequency")



#ggplot() +
#  geom_line(data = estimateKernelDensity(createProperDataframe(countryCode = "ALG", athleteName = "NEMOUR KAYLIA", apparatusInitials = "BB"), 0.25), aes(x, y), color = "blue")
```


```{r}
#for (i in 1:nrow(allWomenBBParticipants)) {
#    row <- allWomenBBParticipants[i, ]
#    row$SimulationResults <- make the list length 10
#}


 # setting up SimulationResults Vector for allWomenBBParticipants
#  for (i in 1:nrow(allWomenBBParticipants)) {
#    row <- allWomenBBParticipants[i, ]
#    row$SimulationResults <- vector("list", n)
#  }
```

```{r}
#for (i in 1:nrow(allWomenBBParticipants)) {
#  row <- allWomenBBParticipants[i, ]
#  toAdd <- createCDFfromKDEandDrawONEscore(estimateKernelDensity(createProperDataframe(countryCode = row$Country, athleteName = row$FullName, apparatusInitials = row$Apparatus), 0.25))
#  print(class(allWomenBBParticipants[i, ]$Simulation))
#  print(class(toAdd))
#  print(toAdd)
#      #toAddList <- list(toAdd)
#      #allWomenBBParticipants[i, ]$SimulationResults[[nthOlympic]] <- toAddList
#}
```
```{r}
#allWomenBBParticipants$SimulationResults <- lapply(1:nrow(allWomenBBParticipants), function(x) vector("list", 10))
#allWomenBBParticipants[2, ]$SimulationResults[[1]][[3]] <- 3

```

```{r}
#allWomenBBParticipants$SimulationResults[[i]][[nthOlympic]] <- toAdd
```






## OVERALL ALGO: runOlympicsNTimes
```{r}
# OVERALL ALGO: runOlympicsNTimes
# input: n
# uses all sorts of helper functions


runOlympicsNTimes <- function(n, allWomenBBParticipants, allWomenFXParticipants, allWomenUBParticipants, allWomenVTParticipants){
  
 
  
  # 1. running the Women's BB n times
  BBParticipants_copied <- allWomenBBParticipants
  
  BBParticipants_copied$SimulationResults <- lapply(1:nrow(BBParticipants_copied), function(x) vector("list", n))
  for (nthOlympic in 1:n){
    
    # each nthOlympic-iteration of the Olympics, this is filling out the nthOlympic-index of each athlete's SimulationResults vector
    for (i in 1:nrow(BBParticipants_copied)) {
      row <- BBParticipants_copied[i, ]
      toAdd <- createCDFfromKDEandDrawONEscore(estimateKernelDensity(createProperDataframe(countryCode = row$Country, athleteName = row$FullName, apparatusInitials = row$Apparatus), 0.25))
    
      BBParticipants_copied[i, ]$SimulationResults[[1]][[nthOlympic]] <- toAdd
    }
    print(paste(nthOlympic, "th olympic done for Women's BB"))
    
  }
  
  #return(BBParticipants_copied)
  
  
    
    
  
  
  
  
  # 2. running the Women's FX n times
  FXParticipants_copied <- allWomenFXParticipants
  
  FXParticipants_copied$SimulationResults <- lapply(1:nrow(FXParticipants_copied), function(x) vector("list", n))
  for (nthOlympic in 1:n){
    
    # each nthOlympic-iteration of the Olympics, this is filling out the nthOlympic-index of each athlete's SimulationResults vector
    for (i in 1:nrow(FXParticipants_copied)) {
      row <- FXParticipants_copied[i, ]
      toAdd <- createCDFfromKDEandDrawONEscore(estimateKernelDensity(createProperDataframe(countryCode = row$Country, athleteName = row$FullName, apparatusInitials = row$Apparatus), 0.25))
    
      FXParticipants_copied[i, ]$SimulationResults[[1]][[nthOlympic]] <- toAdd
    }
    print(paste(nthOlympic, "th olympic done for Women's FX"))
    
  }
  
  #return(FXParticipants_copied)
  
  
  
  # 3. running the Women's UB n times
  UBParticipants_copied <- allWomenUBParticipants
  
  UBParticipants_copied$SimulationResults <- lapply(1:nrow(UBParticipants_copied), function(x) vector("list", n))
  for (nthOlympic in 1:n){
    
    # each nthOlympic-iteration of the Olympics, this is filling out the nthOlympic-index of each athlete's SimulationResults vector
    for (i in 1:nrow(UBParticipants_copied)) {
      row <- UBParticipants_copied[i, ]
      toAdd <- createCDFfromKDEandDrawONEscore(estimateKernelDensity(createProperDataframe(countryCode = row$Country, athleteName = row$FullName, apparatusInitials = row$Apparatus), 0.25))
    
      UBParticipants_copied[i, ]$SimulationResults[[1]][[nthOlympic]] <- toAdd
    }
    print(paste(nthOlympic, "th olympic done for Women's UB"))
    
  }
  
  #return(UBParticipants_copied)
  
  
  
  
  
  
  
  # 4. running the Women's VT n times
  VTParticipants_copied <- allWomenVTParticipants
  
  VTParticipants_copied$SimulationResults <- lapply(1:nrow(VTParticipants_copied), function(x) vector("list", n))
  for (nthOlympic in 1:n){
    
    # each nthOlympic-iteration of the Olympics, this is filling out the nthOlympic-index of each athlete's SimulationResults vector
    for (i in 1:nrow(VTParticipants_copied)) {
      row <- VTParticipants_copied[i, ]
      toAdd <- createCDFfromKDEandDrawONEscore(estimateKernelDensity(createProperDataframe(countryCode = row$Country, athleteName = row$FullName, apparatusInitials = row$Apparatus), 0.25))
    
      VTParticipants_copied[i, ]$SimulationResults[[1]][[nthOlympic]] <- toAdd
    }
    print(paste(nthOlympic, "th olympic done for Women's VT"))
    
  }
  
  #return(VTParticipants_copied)
  
  
  
  
  # RETURN FOUR DATAFRAMES
  return(list(BBResults = BBParticipants_copied, FXResults = FXParticipants_copied, UBResults = UBParticipants_copied, VTResults = VTParticipants_copied))
  
  
}


```



```{r}
# sanityCheck: runOlympicsNTimes

a = runOlympicsNTimes(100, allWomenBBParticipants, allWomenFXParticipants, allWomenUBParticipants, allWomenVTParticipants)

#a <- a %>% 
#  mutate(mean = sapply(SimulationResults, function(x) mean(unlist(x))))
```
```{r}
aBB <- a$BBResults

aBB <- aBB %>% 
  mutate(mean = sapply(SimulationResults, function(x) mean(unlist(x))))


aUB <- a$UBResults

aUB <- aUB %>% 
  mutate(mean = sapply(SimulationResults, function(x) mean(unlist(x))))


aFX <- a$FXResults

aFX <- aFX %>% 
  mutate(mean = sapply(SimulationResults, function(x) mean(unlist(x))))


aVT <- a$VTResults

aVT <- aVT %>% 
  mutate(mean = sapply(SimulationResults, function(x) mean(unlist(x))))

```

```{r}
BBResults <- aBB

# Convert all list columns in BBResults to character strings
BBResults[] <- lapply(BBResults, function(x) {
  if (is.list(x)) {
    sapply(x, toString)
  } else {
    x
  }
})

# Now save the modified data frame to a CSV file
write.csv(BBResults, file = "BBResults.csv", row.names = FALSE)








UBResults <- aUB

# Convert all list columns in BBResults to character strings
UBResults[] <- lapply(UBResults, function(x) {
  if (is.list(x)) {
    sapply(x, toString)
  } else {
    x
  }
})

# Now save the modified data frame to a CSV file
write.csv(UBResults, file = "UBResults.csv", row.names = FALSE)









FXResults <- aFX

# Convert all list columns in BBResults to character strings
FXResults[] <- lapply(FXResults, function(x) {
  if (is.list(x)) {
    sapply(x, toString)
  } else {
    x
  }
})

# Now save the modified data frame to a CSV file
write.csv(FXResults, file = "FXResults.csv", row.names = FALSE)










VTResults <- aVT

# Convert all list columns in BBResults to character strings
VTResults[] <- lapply(VTResults, function(x) {
  if (is.list(x)) {
    sapply(x, toString)
  } else {
    x
  }
})

# Now save the modified data frame to a CSV file
write.csv(VTResults, file = "VTResults.csv", row.names = FALSE)

```



