---
title: |
  | Somersaulting to Gold:
  | Optimizing USA’s Artistic Gymnastics Team Selection Strategy
author: "Emily Zhao, Elyse McFalls, Young Jun, Evan Kim"
geometry: "left=2cm,right=2cm,top=2cm,bottom=2cm"
date: "2023-11-20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

&nbsp;&nbsp;&nbsp;&nbsp; Gymnastics has swiftly risen to become one of America's cherished pastimes, with recent polls revealing it to be the most anticipated Olympic event among Americans.$^1$ This heightened enthusiasm is largely attributed to the historical success the U.S. has enjoyed in the Olympics, particularly in women's artistic gymnastics. Dominant performances by teams like the Final Five in 2016 and athletes like Simone Biles (active 2011 - current) have brought immense prominence to the sport and its athletes.$^2$ While the U.S. men's rhythmic gymnastics team may not be as dominant, they have consistently secured top-five placements in team events at the Olympics and have bolstered decorated athletes like Khoi Young (active 2018 - current) in recent years.$^3$

&nbsp;&nbsp;&nbsp;&nbsp; We expect that millions of Americans are anticipating the gymnastics events at the 2024 Olympic Games in Paris, France.$^4$ This anticipation is coupled with the expectation of U.S. dominance at the Olympics, mirroring the success we have seen in the past. One may ask then: How can we ensure that the U.S. reigns supreme? The answer lies in assembling formidable teams capable of winning the most medals.

&nbsp;&nbsp;&nbsp;&nbsp; Historically, U.S. Olympic team rosters are shaped by the results of the U.S. Olympic Team Trials. The trials will be hosted in June, 2024, for this upcoming cycle.$^5$ Here, each invited athlete's performance determines their spot on the team. Athletes are required to complete all apparatuses twice (4 for women, 6 for men), and scores from each event (8 for women, 12 for men) are combined to generate a final score. The selection committee then uses a combination of the competition results and the teams’ needs to decide on the final rosters. In the last Olympic cycle, the top two performers for women and the top performer for men at the trials secured automatic spots, while the remaining slots were determined by the selection committee.$^6$ Given this meticulous process, it will be some time before the U.S. Olympic gymnastics teams are unveiled, and even longer before we can assess how they will perform on the big stage. The selection committee also faces the arduous task of determining the optimal team makeup. This season, the challenge is particularly difficult for the women's team given the abundance of strong candidates.$^7$

&nbsp;&nbsp;&nbsp;&nbsp; In this paper, we present a simulation-based approach to determine the best U.S. Olympic men and women’s gymnastic teams for the 2024 Paris Olympics. Our method utilizes historical data on each athlete’s performances to simulate pseudo-Olympic data to see how well the U.S. will fare under different team makeups. We imagine that our algorithmic approach would be useful supplementary material for the selection committee to consider when finalizing the roster. Moreover, the results of these simulations may also be enjoyed by fans of the sport who are interested in gaining some insight into what to expect from the Olympics given the athletes’ past scores.


## Methodology 

### Data Collection and Selection Criteria 

### Exploratory Data Analysis

### Weighted Kernel Density Estimates 

## Results

### Average Scenario

### Best-case Scenario

### Worst-case Scenario

## Conclusions 




## Appendix




\newpage
## Sources
1. "Poll: Gymnastics Is America’s Most Highly Anticipated Olympic Sport". SGB Media. 2021. [https://sgbonline.com/poll-gymnastics-is-americans-most-highly-anticipated-olympic-sport/](https://sgbonline.com/poll-gymnastics-is-americans-most-highly-anticipated-olympic-sport/)
2. "How one adjustment helped USA Gymnastics become a power and led to Rio gold". Sports Illustrated. 2016. [https://www.si.com/olympics/2016/08/10/usa-womens-gymnastics-system-rio-olympics-martha-karolyi](https://www.si.com/olympics/2016/08/10/usa-womens-gymnastics-system-rio-olympics-martha-karolyi).
3. United States men's national artistic gymnastics team. Wikipedia. [https://en.wikipedia.org/wiki/United_States_men%27s_national_artistic_gymnastics_team](https://en.wikipedia.org/wiki/United_States_men%27s_national_artistic_gymnastics_team)
4. Paris 2024 - Artistic Gymnastics. [https://www.paris2024.org/en/sport/artistic-gymnastics/](https://www.paris2024.org/en/sport/artistic-gymnastics/)
5. "Minneapolis, Minnesota to host 2024 U.S. Olympic Team Trials – Gymnastics, become Gymnastics City USA 2024". USA Gymnastics. 2023. [https://usagym.org/minneapolis-minnesota-to-host-2024-u-s-olympic-team-trials-gymnastics-become-gymnastics-city-usa-2024/](https://usagym.org/minneapolis-minnesota-to-host-2024-u-s-olympic-team-trials-gymnastics-become-gymnastics-city-usa-2024/)
6. "What to know about the U.S. Olympic gymnastics trials". The Seattle Times. 2021. [https://www.seattletimes.com/sports/olympics/what-to-know-about-the-u-s-olympic-gymnastics-trials/](https://www.seattletimes.com/sports/olympics/what-to-know-about-the-u-s-olympic-gymnastics-trials/)
7. "Picking a strong U.S. gymnastics team is easy. Whom to leave out is hard". The Washington Post. 2023. [https://www.washingtonpost.com/sports/olympics/2023/08/29/us-gymnastics-team-world-championships/](https://www.washingtonpost.com/sports/olympics/2023/08/29/us-gymnastics-team-world-championships/)